print('This program calculates and displays travel expenses')
print('04/16/2023')
print('CTI-110 P1HW1 - Travel')
print('Cory Campbell')
print()
mod1 = float(input('Enter grade for Module 1: '))
mod2 = float(input('Enter grade for Module 2: '))
mod3 = float(input('Enter grade for Module 3: '))
mod4 = float(input('Enter grade for Module 4: '))
mod5 = float(input('Enter grade for Module 5: '))
mod6 = float(input('Enter grade for Module 6: '))
print()
print('------------Results------------')
all_scores = [mod1, mod2, mod3, mod4, mod5, mod6]
lowest_grade = min(all_scores)
highest_grade = max(all_scores)
sum_grade = sum(all_scores)
avg_grade = sum_grade / 6
print(f'{"Lowest Grade:":<20}{lowest_grade:<6.1f}')
print(f'{"Highest Grade:":<20}{highest_grade:<6.1f}')
print(f'{"Sum of Grade:":<20}{sum_grade:<6.1f}')
print(f'{"Average:":<20}{avg_grade:<6.2f}')
print('---------------------------------------')
