print('This program calculates and displays travel expenses')
print('04/15/2023')
print('CTI-110 P2HW1 - Travel')
print('Cory Campbell')

budget = float(input('Enter budget: '))
print()
trav_dest = input('Enter your travel destination: ')
print()
gas = float(input('How much do you think you will spend on gas? '))
print()
accom = float(input('Approximately, how much do you think you will need for accomodation/hotel? '))
print()
food = float(input('Last, how much do you need for food? '))
print()
print('------------Travel Expenses------------')
print(f'{"Location:":<20}{trav_dest:<6}')
print(f'{"Intitial Budget:":<20}${budget:<6.2f}')
print(f'{"Fuel:":<20}${gas:<6.2f}')
print(f'{"Accomodation:":<20}${accom:<6.2f}')
print(f'{"Food:":<20}${food:<6.2f}')
print('---------------------------------------')
print()
rem_bal = budget - gas - accom - food
print(f'{"Remaining Balance:":<20}${rem_bal:<6.2f}')
